import PDFDocument from 'pdfkit';

const LABEL = { HELMET: 'Helmet', CAP_LAMP: 'Cap lamp', REFLECTIVE_VEST: 'Reflective vest', SAFETY_BOOTS: 'Safety boots', GLOVES: 'Gloves', SELF_RESCUER: 'Self-rescuer', DUST_MASK: 'Dust mask', EAR_PROTECTION: 'Ear protection', EYE_PROTECTION: 'Eye protection', GAS_DETECTOR: 'Gas detector' };
const pct = (v) => (v == null ? 'no data' : `${v}%`);

/** One-page A4 daily safety summary. Returns a Buffer. */
export async function buildDailyReportPdf(s) {
  const doc = new PDFDocument({ size: 'A4', margin: 40, info: { Title: `Daily safety report ${s.day}`, Author: 'Mine Guardian' } });
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  const done = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
  const h2 = (t) => doc.moveDown(0.8).font('Helvetica-Bold').fontSize(12).fillColor('#0B1220').text(t).moveDown(0.2).font('Helvetica').fontSize(10).fillColor('#1f2937');
  const line = (k, v) => doc.font('Helvetica-Bold').text(`${k}: `, { continued: true }).font('Helvetica').text(String(v));

  doc.rect(0, 0, doc.page.width, 56).fill('#0B1220');
  doc.fillColor('#F59E0B').fontSize(16).font('Helvetica-Bold').text('Mine Guardian', 40, 16, { continued: true }).fillColor('#ffffff').font('Helvetica').text(`  ·  Daily safety report  ·  ${s.day}`);
  doc.fillColor('#1f2937').fontSize(10).y = 72;

  h2('Compliance');
  line('Check-ins received', s.checkIns);
  line('Reviewed', `${s.reviewed} (compliant ${s.compliant}, non-compliant ${s.nonCompliant}, ${pct(s.compliancePct)})`);
  line('Supervisor overrides / escalations', `${s.overrides} / ${s.escalations}`);
  line('SLA breaches', s.slaBreaches);

  h2('Zones');
  for (const z of s.zones) doc.text(`• ${z.code} ${z.name}: ${z.reviewed} reviewed, ${pct(z.compliancePct)} compliant`, { indent: 8 });

  h2('Most missing PPE');
  if (s.missingPpe.length) for (const m of s.missingPpe) doc.text(`• ${LABEL[m.key] ?? m.key}: ${m.count}`, { indent: 8 });
  else doc.text('None recorded', { indent: 8 });

  h2('Hazards and SOS');
  line('Hazards opened / closed / critical', `${s.hazards.opened} / ${s.hazards.closed} / ${s.hazards.critical}`);
  line('SOS events', s.sosEvents);

  doc.moveDown(2).fontSize(8).fillColor('#6b7280').text('Generated by Mine Guardian. Supervisors decide compliance; the AI only suggests.', { align: 'center' });
  doc.end();
  return done;
}
