// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4z14kw1gK_UwEFB08wXRTUPmWHwpqU94',
    appId: '1:612008981838:web:f79e0e4fc2eb39e4cc1a1f',
    messagingSenderId: '612008981838',
    projectId: 'mine-guardian-b3b81',
    authDomain: 'mine-guardian-b3b81.firebaseapp.com',
    storageBucket: 'mine-guardian-b3b81.firebasestorage.app',
    measurementId: 'G-5YJS985Y25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJS0DJ8ylpdkGBVATccJY_uUfBHFxSbLw',
    appId: '1:612008981838:android:1158b867272a5726cc1a1f',
    messagingSenderId: '612008981838',
    projectId: 'mine-guardian-b3b81',
    storageBucket: 'mine-guardian-b3b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9i_DAWccx0fPs14IEC5Euk-aUREjEfQ',
    appId: '1:612008981838:ios:fc3e5fcb83889327cc1a1f',
    messagingSenderId: '612008981838',
    projectId: 'mine-guardian-b3b81',
    storageBucket: 'mine-guardian-b3b81.firebasestorage.app',
    iosBundleId: 'com.mineguardian.mineGuardian',
  );
}
